name: Auto Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AlmaLinux
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            set -e

            cd /var/www/asilogistics/Logistics_Website_v1

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping old container..."
            docker stop asilogistics_app || true
            docker rm asilogistics_app || true

            echo "Building image..."
            docker build -t asilogistics_app .

            echo "Starting container..."
            docker run -d \
              --name asilogistics_app \
              -p 3000:80 \
              --restart always \
              asilogistics_app
